
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ethan
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();

        fullPathToPhoneCallsXMLjTextField2.setVisible(false);
        fullPathToTextMessagesXMLjTextField1.setVisible(false);
        phoneCallsPromptjLabel2.setVisible(false);
        textMessagesPromptjLabel1.setVisible(false);
        backupNowjButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullPathToPhoneCallsXMLjTextField2 = new javax.swing.JTextField();
        fullPathToTextMessagesXMLjTextField1 = new javax.swing.JTextField();
        phoneCallsPromptjLabel2 = new javax.swing.JLabel();
        textMessagesPromptjLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backupPhoneCallsjRadioButton2 = new javax.swing.JRadioButton();
        backupNowjButton1 = new javax.swing.JButton();
        backupTextMessagesjRadioButton1 = new javax.swing.JRadioButton();

        phoneCallsPromptjLabel2.setText("Enter full path to phone calls XML file below:");

        textMessagesPromptjLabel1.setText("Enter full path to text messages XML file below:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullPathToTextMessagesXMLjTextField1)
                    .addComponent(textMessagesPromptjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullPathToPhoneCallsXMLjTextField2)
                    .addComponent(phoneCallsPromptjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMessagesPromptjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullPathToTextMessagesXMLjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(phoneCallsPromptjLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullPathToPhoneCallsXMLjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backupPhoneCallsjRadioButton2.setText("Backup Phone Calls");
        backupPhoneCallsjRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupPhoneCallsjRadioButton2ActionPerformed(evt);
            }
        });

        backupNowjButton1.setText("Backup Now");
        backupNowjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupNowjButton1ActionPerformed(evt);
            }
        });

        backupTextMessagesjRadioButton1.setText("Backup Text Messages");
        backupTextMessagesjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupTextMessagesjRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(backupPhoneCallsjRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backupTextMessagesjRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(backupNowjButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backupTextMessagesjRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(backupPhoneCallsjRadioButton2)
                .addGap(29, 29, 29)
                .addComponent(backupNowjButton1)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backupTextMessagesjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupTextMessagesjRadioButton1ActionPerformed
        if (backupTextMessagesjRadioButton1.isSelected()) {
            backupNowjButton1.setVisible(true);
            textMessagesPromptjLabel1.setVisible(true);
            fullPathToTextMessagesXMLjTextField1.setVisible(true);
            fullPathToTextMessagesXMLjTextField1.requestFocusInWindow();  // set cursor to blinking in this text field.
        } else {
            if (!backupPhoneCallsjRadioButton2.isSelected()) {
                backupNowjButton1.setVisible(false);
            }
            textMessagesPromptjLabel1.setVisible(false);
            fullPathToTextMessagesXMLjTextField1.setVisible(false);
        }
    }//GEN-LAST:event_backupTextMessagesjRadioButton1ActionPerformed

    private void backupPhoneCallsjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupPhoneCallsjRadioButton2ActionPerformed
        if (backupPhoneCallsjRadioButton2.isSelected()) {
            backupNowjButton1.setVisible(true);
            phoneCallsPromptjLabel2.setVisible(true);
            fullPathToPhoneCallsXMLjTextField2.setVisible(true);
            fullPathToPhoneCallsXMLjTextField2.requestFocusInWindow();  // Set cursor to blinking in this text field.
        } else {
            if (!backupTextMessagesjRadioButton1.isSelected()) {
                backupNowjButton1.setVisible(false);
            }
            phoneCallsPromptjLabel2.setVisible(false);
            fullPathToPhoneCallsXMLjTextField2.setVisible(false);
        }
    }//GEN-LAST:event_backupPhoneCallsjRadioButton2ActionPerformed

    private void backupNowjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupNowjButton1ActionPerformed
        if (backupTextMessagesjRadioButton1.isSelected() && backupPhoneCallsjRadioButton2.isSelected()) {  // User wants to backup both text messages and phone calls.
            TextMessagesBackup backup = new TextMessagesBackup();
            try {
                String[] args = {fullPathToTextMessagesXMLjTextField1.getText()};
                backup.main(args);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "There was a problem trying to backup your text messages: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }

            CallsBackup backup2 = new CallsBackup();

            // Set the list of phone numbers to what was already considered with the text messages (do this solely for efficiency).
            backup2.phoneNumbers = backup.phoneNumbers;

            try {
                String[] args2 = {fullPathToPhoneCallsXMLjTextField2.getText()};
                backup2.main(args2);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "There was a problem trying to backup your phone calls: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (backupPhoneCallsjRadioButton2.isSelected()) {
            CallsBackup backup = new CallsBackup();
            try {
                String[] args = {fullPathToPhoneCallsXMLjTextField2.getText()};
                backup.main(args);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "There was a problem trying to backup your phone calls: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else { // Only backup text messages.
            TextMessagesBackup backup = new TextMessagesBackup();
            try {
                String[] args = {fullPathToTextMessagesXMLjTextField1.getText()};
                backup.main(args);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "There was a problem trying to backup your text messages: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_backupNowjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupNowjButton1;
    private javax.swing.JRadioButton backupPhoneCallsjRadioButton2;
    private javax.swing.JRadioButton backupTextMessagesjRadioButton1;
    private javax.swing.JTextField fullPathToPhoneCallsXMLjTextField2;
    private javax.swing.JTextField fullPathToTextMessagesXMLjTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel phoneCallsPromptjLabel2;
    private javax.swing.JLabel textMessagesPromptjLabel1;
    // End of variables declaration//GEN-END:variables
}
